# Introducción a Numpy

In [6]:
import numpy as np

In [9]:
# Crear una matriz 1D NumPy
array_1d = np.array([1, 2, 3, 4, 5])

print("1D Array:")
print(array_1d)

# Crear matriz 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\n2D Array:")
print(array_2d)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Atributos
print("\nArray Attributes:")
print("Shape:", array_2d.shape)
print("Dimensions:", array_2d.ndim)
print("Data Type:", array_2d.dtype)

# Arreglos de indexación y slicing
print("\nArray Indexing and Slicing:")
print("Element at (1, 2):", array_2d[1, 2])
print("First row:", array_2d[0, :])
print("Second column:", array_2d[:, 1])

# Operaciones de arreglos
print("\nArray Operations:")

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print("Sum:", array_a + array_b)
print("Element-wise product:", array_a * array_b)
print("Matrix product:")
print(np.dot(array_a, array_b))


Array Attributes:
Shape: (3, 3)
Dimensions: 2
Data Type: int64

Array Indexing and Slicing:
Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]

Array Operations:
Sum: [5 7 9]
Element-wise product: [ 4 10 18]
Matrix product:
32


In [11]:
# Operaciones básicas
print("\nBasic Functions:")
print("Mean:", np.mean(array_a))
print("Standard Deviation:", np.std(array_b))
print("Max Value:", np.max(array_a))
print("Index of Max Value:", np.argmax(array_a))


Basic Functions:
Mean: 2.0
Standard Deviation: 0.816496580927726
Max Value: 3
Index of Max Value: 2


In [13]:
# Generando arreglos
print("\nGenerating Arrays:")

zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))
random_array = np.random.rand(2, 3)

print("Zeros Array:")
print(zeros_array)

print("Ones Array:")
print(ones_array)

print("Random Array:")
print(random_array)


Generating Arrays:
Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Array:
[[0.18541267 0.94754695 0.32100097]
 [0.91690387 0.78903534 0.74702899]]
