In [15]:
import numpy as np

matrix = np.random.randint(1,11,size=(3,3));

print(matrix)
print("------------------")
print(matrix.T)

[[ 6 10  8]
 [ 5  8  2]
 [ 7  3  2]]
------------------
[[ 6  5  7]
 [10  8  3]
 [ 8  2  2]]
